FROM python:3.8-slim

RUN mkdir -p /app

WORKDIR /app

COPY webserver/src/webserver.py webserver.py
COPY webserver/html/ html

RUN pip3 install --upgrade pip && pip install --no-cache-dir flask gunicorn

EXPOSE 5000

