apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: eventscraper
type: Opaque
data:
  RABBITMQ_USER: Z3Vlc3Q= # "guest"
  RABBITMQ_PASSWORD: Z3Vlc3Q=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-cm
  namespace: eventscraper
data:
  RABBITMQ_HOST: rabbitmq # rabbitmq.eventscraper.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: eventscraper
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: localhost:5000/event_scraper_rabbitmq:4.1
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBITMQ_USER
          - name: RABBITMQ_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBITMQ_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: eventscraper
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp
    - name: management
      protocol: TCP
      port: 15672
      targetPort: management