name: Event Scraper CLI CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  PROJECT_PATH: /home/runner/event_scraper_web

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Save repository path
        run: echo "REPO_PATH=$(pwd)" >> $GITHUB_ENV

  create_venv:
    runs-on: self-hosted
    needs: checkout
    container:
      image: python:3.12-slim
      options: --mount type=bind,source=${{ github.workspace }},target=${{ env.PROJECT_PATH }}
    steps:
      - name: Create Virtual Environment
        run: python -m venv ${{ env.PROJECT_PATH }}
      - name: Save venv path
        run: echo "VENV_PATH=${{ env.PROJECT_PATH }}" >> $GITHUB_ENV

  install_dependencies:
    runs-on: self-hosted
    needs: create_venv
    container:
      image: python:3.12-slim
      options: --mount type=bind,source=${{ github.workspace }},target=${{ env.PROJECT_PATH }}
    steps:
      - name: Install Dependencies
        run: ${{ env.PROJECT_PATH }}/bin/pip install -r ${{ env.PROJECT_PATH }}/requirements.txt

  run_scraper:
    runs-on: self-hosted
    needs: install_dependencies
    container:
      image: python:3.12-slim
      options: --mount type=bind,source=${{ github.workspace }},target=${{ env.PROJECT_PATH }}
    steps:
      - name: Run Event Scraper
        run: ${{ env.PROJECT_PATH }}/bin/python ${{ env.PROJECT_PATH }}/event_scraper/src/init.py
